server:
  port: 5003

spring:
  application:
    name: booking

  datasource:
    url: "jdbc:mysql://localhost:3306/salon_booking_db?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rathod@9586
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest


  mail:
    host: smtp.gmail.com
    port: 587
    username: vilasrathod8556@gmail.com
    password: Vilas@8556
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: read_only
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

razorpay:
  api:
    key: rzp_test_p05gsP0O9199nI
    secret: rklxNAQymw4rgmkQMRRgw4An

stripe:
  api:
    key: sk_test_51OY24RHktfaHaMpma35wc5WWVeCTtr23N5crNHIT0RkFlc7tQkAqdoH09x4QbHOfZfQf6MIvcio4lTJFllnOxGxj00dI1RvRn5


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Payment Service"
    description: "Payment Service API For Salon Booking System"
    version: "1.0.0"